### ISSUE TITLE
bukkit error

### ISSUE THREAD

**Issue by youare0912** [ProfliXx/MobControl#5]
Cause of error : Server start
it paper bukkit
Minecraft VER : 1.16.4 

![77](https://user-images.githubusercontent.com/78303680/106383520-ef777a00-6409-11eb-8094-a6beb5d2cc79.PNG)

ERROR LOG

[19:42:12] [Craft Scheduler Thread - 1/INFO]: [MobControl]  MobControl | There is no new updates available.
[19:42:17] [Server thread/INFO]: Plugins (1): MobControl
[19:42:19] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobControl v1.6.0
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R3.entity.CraftPiglin cannot be cast to org.bukkit.entity.Player
	at me.proflixx.mobcontrol.listeners.creaturespawn.MobsSpawns.onCreatureSpawn(MobsSpawns.java:41) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-416]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:680) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:601) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1187) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntitySerialized(WorldServer.java:1098) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntitySerialized(WorldServer.java:1094) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntityTeleport(WorldServer.java:1106) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.Entity.teleportTo(Entity.java:2605) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.Entity.b(Entity.java:2562) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.Entity.doPortalTick(Entity.java:2186) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.Entity.postTick(Entity.java:413) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:846) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.World.a(World.java:887) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by ProfliXx** [comment]
Thanks for posting the issue. Will be fixed in next update.

**Comment by ProfliXx** [comment]
Fixed. Check out new update.
